### ISSUE TITLE
Wrong path for import?

### ISSUE THREAD

**Issue by pcasaretto** [heroku/go-getting-started#2]
I was wondering if we should use regular import paths or Godep specific ones like suggested here: https://github.com/heroku/go-getting-started/blob/15d873235f89835cd358fa815e7fe1c011efcbb3/cmd/go-getting-started/main.go#L8

It seems to me that using Godep specific paths is bad form.

**Comment by freeformz** [comment]
That is the way to use rewritten paths so that we use the correct version w/o having to use godep to build the code. In essence this makes the code "go-gettable" (`go get github.com/heroku/go-getting-started/...`).

Once Go 1.6 is released I'll update all of the examples/getting started bits to use the `vendor/` directory and make callouts for go 1.5 and older versions of go. 

For now though it's easier to get up and running with rewritten import paths.
